[package]
name = "day11"
version = "0.1.0"
edition = "2021"
default-run = "part2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = "0.12.2"
